name: Test and Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build server
      run: |
        # Initialize go module if not exists
        if [ ! -f go.mod ]; then
          go mod init relay-server
        fi
        
        # Get dependencies
        go get github.com/gorilla/mux
        go get github.com/gorilla/websocket
        
        # Build the server
        go build -o relay-server relay-server.go
    
    - name: Start local server
      run: |
        # Start server in background
        ./relay-server &
        SERVER_PID=$!
        echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
        
        # Wait for server to be ready
        echo "Waiting for server to start..."
        for i in {1..30}; do
          if curl -f http://localhost:8080/health 2>/dev/null; then
            echo "✅ Server is ready!"
            break
          fi
          echo "  Attempt $i/30..."
          sleep 1
        done
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Run benchmark tests
      run: |
        
        # Install dependencies
        npm install ws --no-save
        
        # Create a simple benchmark
        cat > benchmark.js << 'EOF'
        const WebSocket = require('ws');
        const fs = require('fs');
        
        async function runBenchmark() {
            const results = {
                timestamp: new Date().toISOString(),
                metrics: {
                    messages_per_second: 0,
                    bandwidth_mbps: 0,
                    total_messages: 0,
                    total_bytes: 0,
                    connected_users: 0
                },
                test_duration_ms: 0
            };
            
            console.log('🚀 Starting benchmark...');
            const startTime = Date.now();
            
            // Test WebSocket connections
            const ws1 = new WebSocket('ws://localhost:8080/ws/test1');
            const ws2 = new WebSocket('ws://localhost:8080/ws/test2');
            
            let messagesSent = 0;
            let messagesReceived = 0;
            let bytesTransferred = 0;
            
            await new Promise((resolve) => {
                ws1.on('open', () => {
                    console.log('Client 1 connected');
                    
                    // Send messages for 5 seconds
                    const interval = setInterval(() => {
                        if (Date.now() - startTime > 5000) {
                            clearInterval(interval);
                            
                            // Calculate results
                            const duration = (Date.now() - startTime) / 1000;
                            results.metrics.messages_per_second = messagesReceived / duration;
                            results.metrics.total_messages = messagesReceived;
                            results.metrics.total_bytes = bytesTransferred;
                            results.metrics.bandwidth_mbps = (bytesTransferred * 8) / (duration * 1000000);
                            results.metrics.connected_users = 2;
                            results.test_duration_ms = Date.now() - startTime;
                            
                            ws1.close();
                            ws2.close();
                            resolve();
                            return;
                        }
                        
                        const msg = JSON.stringify({
                            id: messagesSent++,
                            data: 'x'.repeat(1000)
                        });
                        ws1.send(msg);
                        bytesTransferred += msg.length;
                    }, 10);
                });
                
                ws2.on('message', () => {
                    messagesReceived++;
                });
                
                ws2.on('open', () => {
                    console.log('Client 2 connected');
                });
            });
            
            console.log('✅ Benchmark complete!');
            console.log(`  Throughput: ${results.metrics.messages_per_second.toFixed(2)} msg/s`);
            console.log(`  Bandwidth: ${results.metrics.bandwidth_mbps.toFixed(2)} Mbps`);
            
            // Save results
            fs.writeFileSync('performance-report.json', JSON.stringify({
                results: results,
                report_markdown: generateMarkdown(results),
                report_html: generateHTML(results)
            }, null, 2));
            
            return results;
        }
        
        function generateMarkdown(results) {
            return '# Performance Report\\n' +
        '\\n' +
        '**Generated:** ' + results.timestamp + '\\n' +
        '\\n' +
        '## Metrics\\n' +
        '- **Throughput:** ' + results.metrics.messages_per_second.toFixed(2) + ' msg/s\\n' +
        '- **Bandwidth:** ' + results.metrics.bandwidth_mbps.toFixed(2) + ' Mbps\\n' +
        '- **Total Messages:** ' + results.metrics.total_messages + '\\n' +
        '- **Test Duration:** ' + results.test_duration_ms + 'ms\\n';
        }
        
        function generateHTML(results) {
            return '<!DOCTYPE html>\\n' +
                '<html>\\n' +
                '<head><title>Performance Report</title></head>\\n' +
                '<body>\\n' +
                '<h1>Performance Report</h1>\\n' +
                '<p>Generated: ' + results.timestamp + '</p>\\n' +
                '<ul>\\n' +
                '<li>Throughput: ' + results.metrics.messages_per_second.toFixed(2) + ' msg/s</li>\\n' +
                '<li>Bandwidth: ' + results.metrics.bandwidth_mbps.toFixed(2) + ' Mbps</li>\\n' +
                '</ul>\\n' +
                '</body>\\n' +
                '</html>';
        }
        
        runBenchmark().catch(console.error);
        EOF
        
        node benchmark.js
        
        # Generate HTML and Markdown files (with error handling)
        if [ -f performance-report.json ]; then
          cat performance-report.json | python3 -c "import json, sys; data=json.load(sys.stdin); print(data.get('report_markdown', '# No report'))" > performance-report.md
          cat performance-report.json | python3 -c "import json, sys; data=json.load(sys.stdin); print(data.get('report_html', '<html><body>No report</body></html>'))" > performance-report.html
        else
          echo "# Test Report - Failed" > performance-report.md
          echo "<html><body>Test failed</body></html>" > performance-report.html
          echo '{"results":{"metrics":{"messages_per_second":0}}}' > performance-report.json
        fi
    
    - name: Stop server
      if: always()
      run: |
        if [ ! -z "$SERVER_PID" ]; then
          kill $SERVER_PID || true
        fi
    
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages-existing
      continue-on-error: true
    
    - name: Prepare GitHub Pages content
      run: |
        echo "📄 Preparing GitHub Pages content..."
        
        # Create fresh gh-pages directory
        mkdir -p gh-pages/reports
        
        # Copy existing reports if gh-pages branch exists
        if [ -d gh-pages-existing/reports ]; then
          echo "Found existing reports, copying..."
          cp -r gh-pages-existing/reports/* gh-pages/reports/ || true
        fi
        
        # Create reports directory for this commit
        mkdir -p gh-pages/reports/${{ github.sha }}
        
        # Copy performance reports
        cp performance-report.html gh-pages/reports/${{ github.sha }}/
        cp performance-report.md gh-pages/reports/${{ github.sha }}/
        cp performance-report.json gh-pages/reports/${{ github.sha }}/
        
        # Extract metrics using Python (more reliable than jq)
        THROUGHPUT=$(cat performance-report.json | python3 -c "import json, sys; d=json.load(sys.stdin); print(d.get('results',{}).get('metrics',{}).get('messages_per_second',0))")
        LATENCY=$(cat performance-report.json | python3 -c "import json, sys; d=json.load(sys.stdin); print(d.get('results',{}).get('test_duration_ms',0))")
        BANDWIDTH=$(cat performance-report.json | python3 -c "import json, sys; d=json.load(sys.stdin); print(d.get('results',{}).get('metrics',{}).get('bandwidth_mbps',0))")
        TOTAL_MESSAGES=$(cat performance-report.json | python3 -c "import json, sys; d=json.load(sys.stdin); print(d.get('results',{}).get('metrics',{}).get('total_messages',0))")
        TOTAL_BYTES=$(cat performance-report.json | python3 -c "import json, sys; d=json.load(sys.stdin); print(d.get('results',{}).get('metrics',{}).get('total_bytes',0))")
        
        # Create or update index (using Python instead of jq)
        python3 << EOF
import json
import os
from datetime import datetime

index_file = 'gh-pages/reports/index.json'
new_report = {
    "commit": "${{ github.sha }}",
    "timestamp": datetime.utcnow().isoformat() + "Z",
    "actor": "${{ github.actor }}",
    "branch": "${{ github.ref_name }}",
    "throughput": float("$THROUGHPUT"),
    "latency": float("$LATENCY"),
    "bandwidth": float("$BANDWIDTH"),
    "totalMessages": int(float("$TOTAL_MESSAGES")),
    "totalBytes": int(float("$TOTAL_BYTES"))
}

if os.path.exists(index_file):
    with open(index_file, 'r') as f:
        data = json.load(f)
else:
    data = {"reports": []}

data["reports"].insert(0, new_report)
data["reports"] = data["reports"][:50]  # Keep last 50 reports

with open(index_file, 'w') as f:
    json.dump(data, f, indent=2)
EOF
        
        
        # Copy dashboard files
        cp -r docs/* gh-pages/ 2>/dev/null || true
        
        echo "✅ GitHub Pages content prepared"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        keep_files: true
        commit_message: "📊 Update performance reports for ${{ github.sha }}"
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: performance-report-${{ github.sha }}
        path: |
          performance-report.md
          performance-report.html
          performance-report.json
        retention-days: 90
    
    - name: Summary
      run: |
        echo "## 📊 Benchmark Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        cat performance-report.md >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Dashboard" >> $GITHUB_STEP_SUMMARY
        echo "View full dashboard at: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY